services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: questify
    ports:
      - '5433:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - questifynetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - '15432:80'
    depends_on:
      - db
    networks:
      - questifynetwork

  springbootapp:
    build:
      dockerfile: Dockerfile
      context: ./questifysharedapi
    container_name: questifyapi
    restart: on-failure
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - questifynetwork
    environment:
      - POSTGRES_HOST=db

  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./questifyshared
    container_name: questify_frontend
    restart: on-failure
    depends_on:
      - springbootapp
    ports:
      - '3000:3000'
    networks: 
      - questifynetwork
    expose:
      - 3000
networks:
  questifynetwork:
    driver: bridge