spring:
  datasource:
    url: jdbc:postgresql://ep-divine-violet-a60j3p0h-pooler.us-west-2.aws.neon.tech/questionhub?user=questionhub_owner&password=npg_fObXv0LhjZ2n&sslmode=require
    username: postgres
    password: vasco123
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4-turbo
    ollama:
      chat:
        options:
          temperature: 0.0

# Production
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/questionhub
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4-turbo
    ollama:
      chat:
        options:
          temperature: 0.0